######################################################################
# Automatically generated by qmake (3.0) Sun Jan 4 18:57:49 2015
######################################################################

TEMPLATE = app
TARGET = load_test
INCLUDEPATH += . .. 
QMAKE_CXXFLAGS += -std=c++11 -w `gdal-config --cflags`
LIBS += -lX11 `gdal-config --libs`
QT += widgets

# Input
SOURCES += load_img.cpp
